name: MinePlace
version: 1.1.2
authors:
  - Northernside
  - unordentlich
  - Zeichenfolge
  - L3nnart_
  - InspectorRex
main: social.northernside.mineplace.MinePlace

commands:
  ping:
    description: Display your network latency
  team:
    description: Manage teams
  modtool:
    description: Secret!
  rank:
    description: Secret!
  bypasscooldown:
    description: Secret!