name: MinePlace
version: 1.4
authors:
  - Northernside
  - unordentlich
  - Zeichenfolge
  - L3nnart_
  - InspectorRex
main: de.northernsi.mineplace.MinePlace
description: MinePlace offers a completely new gaming experience in Minecraft. As a parody of r/place, a world-renowned reddit community project, this project offers endless possibilities to immortalise one's creativity in MinePlace, in addition to many varied features such as joining game teams or a large number of colours.
depend: [ ProtocolLib ]

commands:
  ping:
    description: Display your or other users' network latency.
  team:
    description: Manage teams.
  modtool:
    description: Opens the mod tool menu.
  rank:
    description: Sets the rank of an user.
  bypasscooldown:
    description: Bypasses the placing cooldown.
  rules:
    description: Shows the rules.